print("=+=+=+=+ Data Diri Mahasiswa =+=+=+=+")
nim = input("NIM : ")
nama = input("Nama : ")
jurusan = input("Jurusan : ")
alamat = input("Alamat : ")
print('--------------------------------')
print("Hasil Cetak data diatas adalah")
print("NIM     : " +str(nim))
print("Nama    : " +str(nama))
print("Jurusan : " +str(jurusan))
print("alamat  : " +str(alamat))